// <auto-generated />
using System;
using BrasilBurger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrasilBurger.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrasilBurger.Models.Burger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("prix");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("burgers", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("text")
                        .HasColumnName("adresse");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mot_de_passe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseLivraison")
                        .HasColumnType("text")
                        .HasColumnName("adresse_livraison");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_commande");

                    b.Property<DateTime?>("DateLivraison")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_livraison");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etat");

                    b.Property<int?>("LivreurId")
                        .HasColumnType("integer")
                        .HasColumnName("livreur_id");

                    b.Property<bool>("Payee")
                        .HasColumnType("boolean")
                        .HasColumnName("payee");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<string>("TypeLivraison")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type_livraison");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("LivreurId");

                    b.HasIndex("ZoneId");

                    b.ToTable("commandes", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Models.CommandeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BurgerId")
                        .HasColumnType("integer")
                        .HasColumnName("burger_id");

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer")
                        .HasColumnName("commande_id");

                    b.Property<int?>("ComplementId")
                        .HasColumnType("integer")
                        .HasColumnName("complement_id");

                    b.Property<int?>("ComplementId1")
                        .HasColumnType("integer");

                    b.Property<int?>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("numeric")
                        .HasColumnName("prix_unitaire");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.HasKey("Id");

                    b.HasIndex("BurgerId");

                    b.HasIndex("CommandeId");

                    b.HasIndex("ComplementId");

                    b.HasIndex("ComplementId1");

                    b.HasIndex("MenuId");

                    b.ToTable("commande_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_CommandeItem_Type", "(\r\n                        (burger_id IS NOT NULL AND menu_id IS NULL AND complement_id IS NULL)\r\n                     OR (burger_id IS NULL AND menu_id IS NOT NULL AND complement_id IS NULL)\r\n                     OR (burger_id IS NULL AND menu_id IS NULL AND complement_id IS NOT NULL)\r\n                    )");
                        });
                });

            modelBuilder.Entity("BrasilBurger.Models.Complement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("prix");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("complements", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Models.Livreur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vehicule")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicule");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("livreurs", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<int?>("BoissonId")
                        .HasColumnType("integer")
                        .HasColumnName("boisson_id");

                    b.Property<int>("BurgerId")
                        .HasColumnType("integer")
                        .HasColumnName("burger_id");

                    b.Property<int?>("ComplementId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComplementId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("FriteId")
                        .HasColumnType("integer")
                        .HasColumnName("frite_id");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("prix");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BoissonId");

                    b.HasIndex("BurgerId");

                    b.HasIndex("ComplementId");

                    b.HasIndex("ComplementId1");

                    b.HasIndex("FriteId");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer")
                        .HasColumnName("commande_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_paiement");

                    b.Property<string>("Methode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("methode");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric")
                        .HasColumnName("montant");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.ToTable("paiements", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<decimal>("PrixLivraison")
                        .HasColumnType("numeric")
                        .HasColumnName("prix_livraison");

                    b.Property<string[]>("Quartiers")
                        .HasColumnType("text[]")
                        .HasColumnName("quartiers");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("BrasilBurger.Models.Commande", b =>
                {
                    b.HasOne("BrasilBurger.Models.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrasilBurger.Models.Livreur", "Livreur")
                        .WithMany("Commandes")
                        .HasForeignKey("LivreurId");

                    b.HasOne("BrasilBurger.Models.Zone", "Zone")
                        .WithMany("Commandes")
                        .HasForeignKey("ZoneId");

                    b.Navigation("Client");

                    b.Navigation("Livreur");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("BrasilBurger.Models.CommandeItem", b =>
                {
                    b.HasOne("BrasilBurger.Models.Burger", "Burger")
                        .WithMany("CommandeItems")
                        .HasForeignKey("BurgerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BrasilBurger.Models.Commande", "Commande")
                        .WithMany("CommandeItems")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrasilBurger.Models.Complement", "Complement")
                        .WithMany()
                        .HasForeignKey("ComplementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BrasilBurger.Models.Complement", null)
                        .WithMany("CommandeItems")
                        .HasForeignKey("ComplementId1");

                    b.HasOne("BrasilBurger.Models.Menu", "Menu")
                        .WithMany("CommandeItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Burger");

                    b.Navigation("Commande");

                    b.Navigation("Complement");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("BrasilBurger.Models.Livreur", b =>
                {
                    b.HasOne("BrasilBurger.Models.Zone", "Zone")
                        .WithMany("Livreurs")
                        .HasForeignKey("ZoneId");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("BrasilBurger.Models.Menu", b =>
                {
                    b.HasOne("BrasilBurger.Models.Complement", "Boisson")
                        .WithMany()
                        .HasForeignKey("BoissonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BrasilBurger.Models.Burger", "Burger")
                        .WithMany("Menus")
                        .HasForeignKey("BurgerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrasilBurger.Models.Complement", null)
                        .WithMany("MenusBoisson")
                        .HasForeignKey("ComplementId");

                    b.HasOne("BrasilBurger.Models.Complement", null)
                        .WithMany("MenusFrite")
                        .HasForeignKey("ComplementId1");

                    b.HasOne("BrasilBurger.Models.Complement", "Frite")
                        .WithMany()
                        .HasForeignKey("FriteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Boisson");

                    b.Navigation("Burger");

                    b.Navigation("Frite");
                });

            modelBuilder.Entity("BrasilBurger.Models.Paiement", b =>
                {
                    b.HasOne("BrasilBurger.Models.Commande", "Commande")
                        .WithMany("Paiements")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("BrasilBurger.Models.Burger", b =>
                {
                    b.Navigation("CommandeItems");

                    b.Navigation("Menus");
                });

            modelBuilder.Entity("BrasilBurger.Models.Client", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("BrasilBurger.Models.Commande", b =>
                {
                    b.Navigation("CommandeItems");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("BrasilBurger.Models.Complement", b =>
                {
                    b.Navigation("CommandeItems");

                    b.Navigation("MenusBoisson");

                    b.Navigation("MenusFrite");
                });

            modelBuilder.Entity("BrasilBurger.Models.Livreur", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("BrasilBurger.Models.Menu", b =>
                {
                    b.Navigation("CommandeItems");
                });

            modelBuilder.Entity("BrasilBurger.Models.Zone", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Livreurs");
                });
#pragma warning restore 612, 618
        }
    }
}
