# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute

# # Routes API
# api:
#     resource: ../config/routes/api.yaml
#     prefix: /api

# # Routes Gestion
# gestion:
#     resource: ../config/routes/gestion.yaml
#     prefix: /gestion

# config/routes.yaml

# Route racine
home:
    path: /
    controller: App\Controller\HomeController::index

# Routes API
api:
    resource: routes/api.yaml
    prefix: /api

# Routes Gestion
gestion:
    resource: routes/gestion.yaml
    prefix: /gestion

# Routes automatiques des contrôleurs
    
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

